version: '3.5'
services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:8000"
      - "443:443"
    volumes:
      - ./build:/var/www/html:ro
      - ./docker/web/magento2.template:/etc/nginx/conf.d/magento2.template
      - ./docker/web/ssl:/etc/nginx/ssl
      - ./docker/web/auth:/etc/nginx/auth
      - ./docker/var/log/nginx:/var/log/nginx
    environment:
      - NGINX_HOST=magento2.local
      - NGINX_PORT=8000
      - NGINX_ROOT=/var/www/html
      - NGINX_MAX_BODY_SIZE=10M
      - PHP_FPM_HOST=app
      - PHP_FPM_PORT=9000
      - ESC=$$
    depends_on:
      - app
    networks:
      magento2:
        ipv4_address: 172.20.100.2
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/magento2.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  app:
    build:
      context: docker/app/
    restart: always
    expose:
      - 9000
    volumes:
      - ./build:/var/www/html
      - ./docker/app/ini/php.ini:/usr/local/etc/php/php.ini
      - ./docker/app/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/var/log/php-fpm:/var/log/php-fpm
#      - ./docker/app/ini/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
      - cache
    networks:
      magento2:
        ipv4_address: 172.20.100.3

  db:
    image: mysql:5.7
    restart: always
    env_file: ./docker/.env
    environment:
      MYSQL_ROOT_PASSWORD: $${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: $${DATABASE_NAME}
      MYSQL_USER: $${DATABASE_USER}
      MYSQL_PASSWORD: $${DATABASE_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/db/init.d:/docker-entrypoint-initdb.d
      - ./docker/db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      magento2:
        ipv4_address: 172.20.100.4

  cache:
    image: redis:latest
    networks:
      magento2:
        ipv4_address: 172.20.100.5

volumes:
    dbdata:

networks:
  magento2:
    name: magento2_global
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.100.0/24
