version: '3.5'
services:
  web:
    image: nginx:latest
    ports:
      - "80:8000"
      - "443:443"
    volumes:
      - ./build:/var/www/html:ro
      - sockdata:/var/run
      - ./.docker/web/ssl:/etc/nginx/certs
      - ./.docker/web/magento2.template:/etc/nginx/conf.d/default.conf
      - ./.docker/var/log/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      magento2:
        ipv4_address: 172.20.100.2

  app:
    build:
      context: .docker/app
      args:
        UID: '1000'
    volumes:
      - ./build:/var/www/html
      - sockdata:/var/run
    depends_on:
      - db
      - cache
    networks:
      magento2:
        ipv4_address: 172.20.100.3

  db:
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento_user
      - MYSQL_PASSWORD=123
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/db/init.d:/docker-entrypoint-initdb.d
      - ./docker/db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      magento2:
        ipv4_address: 172.20.100.4

  cache:
    image: redis:latest
    networks:
      magento2:
        ipv4_address: 172.20.100.5

volumes:
    dbdata:
    sockdata:

networks:
  magento2:
    ipam:
      config:
        - subnet: 172.20.100.0/24
